%YAML 1.2
---
name: git-cola-brlin
version: 'replaced-by-version-script'
version-script: |
  set -eu

  upstream_version="$(
    git \
      -C parts/git-cola/src \
      describe \
      --always \
      --dirty=-d \
      --tags \
    | sed s/^v//
  )"

  packaging_revision="$(
    git \
      describe \
      --abbrev=4 \
      --always \
      --dirty=-d
  )"

  printf -- '%s' "${upstream_version}+pkg-${packaging_revision}"

summary: The highly caffeinated Git GUI
description: |
  git-cola is a powerful Git GUI with a slick and intuitive user interface.

confinement: strict
grade: devel
icon: snap/gui/icon.png

apps:
  git-cola:
    command: >
      env
      GIT_CONFIG_NOSYSTEM=true
      GIT_EXEC_PATH=$SNAP/usr/lib/git-core
      desktop-launch
      git-cola-launch
      git cola
    desktop: share/applications/git-cola.desktop
    plugs:
    - desktop
    - desktop-legacy
    - x11
    - unity7

    - home
    - removable-media

    # SSH remote support
    - ssh-keys

    # For signing commits and tags
    - gpg-keys

    # Network access for remote operations
    - network
    - network-observe
  git-dag:
    command: >
      env
      GIT_CONFIG_NOSYSTEM=true
      GIT_EXEC_PATH=$SNAP/usr/lib/git-core
      desktop-launch
      git dag
    desktop: share/applications/git-dag.desktop
    plugs:
    - desktop
    - desktop-legacy
    - x11
    - unity7

    - home
    - removable-media

    # For signing commits and tags
    - gpg-keys

  git-cola-folder-handler:
    command: >
      env
      GIT_CONFIG_NOSYSTEM=true
      GIT_EXEC_PATH=$SNAP/usr/lib/git-core
      desktop-launch
      git-cola --repo
    desktop: share/applications/git-cola-folder-handler.desktop
    plugs:
    - desktop
    - desktop-legacy
    - x11
    - unity7

    - home
    - removable-media

    # SSH remote support
    - ssh-keys

    # For signing commits and tags
    - gpg-keys

parts:
  # Patches to fix other parts
  patches:
    source: snap/patches
    source-type: local
    plugin: dump

    # DISABLED: Bug #1775582 “`organize:{ /: another-dir/ }` causes the items under host root directory to be copied in another-dir” : Bugs : Snapcraft
    # https://forum.snapcraft.io/t/organize-another-dir-causes-the-items-under-host-root-directory-to-be-copied-in-another-dir/5806
    #organize:
        #/: patches/
    override-build: |
      set -eu

      snapcraftctl build

      mkdir \
        --parents \
        "$SNAPCRAFT_PART_INSTALL"/patches
      mv \
        "$SNAPCRAFT_PART_INSTALL"/*.diff \
        "$SNAPCRAFT_PART_INSTALL"/*.patch \
        "$SNAPCRAFT_PART_INSTALL"/*.sed \
        "$SNAPCRAFT_PART_INSTALL"/patches \
        || true # Empty patches folder is allowed
    stage:
    - patches/*
    override-prime: 'true'

  # Launchers to fix runtime environments
  launchers:
    source: snap/launchers
    source-type: local
    plugin: dump

    override-build: |
      set -eu

      mkdir \
        --parents \
        "$SNAPCRAFT_PART_INSTALL"/bin
      cp \
        --force \
        --verbose \
        *-launch \
        "$SNAPCRAFT_PART_INSTALL"/bin

  # Ubuntu 16.04 doesn't have python-send2trash
  send2trash:
    plugin: python
    process-dependency-links: false
    python-packages:
    - send2trash
    python-version: python2

  git-cola:
    after:
    - desktop-qt5
    - patches
    - send2trash

    build-packages:
    - gettext
    - make
    - rsync

    - python
    - python-pyqt5
    - python-sphinx

    # REPLACED: Git Cola crashed when using Python 3
    # Git Cola crashes with "TypeError: a bytes-like object is required, not 'str'" in confined environment · Issue #849 · git-cola/git-cola
    # https://github.com/git-cola/git-cola/issues/849
    #- python3
    #- python3-pyqt5
    #- python3-sphinx
    stage-packages:
    # REPLACED: by send2trash part
    #- python3-send2trash

    - git-core
    - libdb5.3

    - python
    - python-pyqt5

    # REPLACED: Git Cola crashed when using Python 3
    # Git Cola crashes with "TypeError: a bytes-like object is required, not 'str'" in confined environment · Issue #849 · git-cola/git-cola
    # https://github.com/git-cola/git-cola/issues/849
    #- python3
    #- python3-pyqt5

    source: git://github.com/git-cola/git-cola.git
    source-depth: 200

    plugin: make
    make-parameters:
    - DESTDIR=$SNAPCRAFT_PART_INSTALL
    - prefix=/snap/git-cola-brlin/current
    - install-doc
    organize:
      snap/git-cola-brlin/current/: /
    filesets:
      additional-executables:
      - share/git-cola/bin/*
      appdata:
      - share/appdata/*
      desktop-entries:
      - share/applications/*
      documentation:
      - share/doc/git-cola/*
      executables:
      - bin/*
      icons:
      - share/git-cola/icons/*
      libraries:
      - share/git-cola/lib/*
      localization:
      - share/locale/*

    override-stage: |
      set -eu

      snapcraftctl stage

      # Patch desktop entries
      sed \
        --file "${SNAPCRAFT_STAGE}"/patches/patch-desktop-entries.sed \
        --in-place \
        "${SNAPCRAFT_STAGE}"/share/applications/*.desktop

      # Patch executable shebangs
      # https://github.com/git-cola/git-cola/issues/850
      sed \
        --file "${SNAPCRAFT_STAGE}"/patches/patch-git-cola-shebang.sed \
        --in-place \
        "${SNAPCRAFT_STAGE}"/bin/git-cola \
        "${SNAPCRAFT_STAGE}"/bin/git-dag
    override-prime: |
      set -eu

      snapcraftctl prime

      # REPLACED: Git Cola crashed when using Python 3
      # Git Cola crashes with "TypeError: a bytes-like object is required, not 'str'" in confined environment · Issue #849 · git-cola/git-cola
      # https://github.com/git-cola/git-cola/issues/849
      # Set default python intepreter
      #ln \
        #--force \
        #--symbolic \
        #python3 \
        #"${SNAPCRAFT_PRIME}"/usr/bin/python
